# config_cnn.py

# --- 1. USTAWIENIA ŚWIATA ---
GRID_WIDTH = 40
GRID_HEIGHT = 40
NUM_FOOD = 45

# --- 2. USTAWIENIA AGENTA ---
START_ENERGY = 100
EAT_GAIN = 150
MAX_ENERGY_GAIN_PER_FOOD = 10
MOVE_COST = 2
IDLE_COST = 3

# --- Ustawienia "Mózgu" v26 (Precyzyjny CNN bez Pooling) ---
# Architektura jest w `mikroswiat_cnn.py`
MAX_PERCEPTION_RADIUS = 3   # Mózg widzi 7x7
START_PERCEPTION_RADIUS = 1
VISION_UPGRADES = {
    2: 2,
    5: 3
}

# --- 3. USTAWIENIA PREDATORA ---
PREDATOR_COUNT = 5
PREDATOR_RESPAWN = False
PREDATOR_VISION = 10
PREDATOR_BASE_STRENGTH = 5
PREDATOR_ALLY_BONUS = 2
PREDATOR_ALLY_RADIUS = 3

# --- Mechanika Kosztu Zabójstwa (v17) ---
KILL_LICENSE_LEVEL = 5
KILL_COST_PELLETS = 1

# --- 4. USTAWIENIA EWOLUCJI (GENETIC ALGORITHM) ---
POPULATION_SIZE = 100
NUM_GENERATIONS = 50
MAX_TURNS_PER_GEN = 1000
MUTATION_RATE = 0.05
MUTATION_STRENGTH = 0.5
ELITISM_COUNT = 10

# --- 5. USTAWIENIA ZAPISU ---
MODEL_SAVE_DIR = "best_models_cnn_no_pool" # <-- ZMIANA

# --- 6. USTAWIENIA WIZUALIZACJI ---
CELL_SIZE = 14
WINDOW_WIDTH = GRID_WIDTH * CELL_SIZE
WINDOW_HEIGHT = GRID_HEIGHT * CELL_SIZE
FPS = 15

# --- 7. KOLORY (RGB) ---
COLOR_BG = (20, 20, 20)
COLOR_FOOD = (0, 255, 0)
COLOR_AGENT = (0, 150, 255)
COLOR_PREDATOR = (255, 0, 0)
COLOR_GRID = (40, 40, 40)