# config_coevo.py

# --- 1. USTAWIENIA ŚWIATA ---
GRID_WIDTH = 40
GRID_HEIGHT = 40
NUM_FOOD = 45
NUM_WALLS = 50

# --- 2. USTAWIENIA AGENTA ---
START_ENERGY = 100
EAT_GAIN = 150
MAX_ENERGY_GAIN_PER_FOOD = 10
MOVE_COST = 1
IDLE_COST = 3
WALL_HIT_PENALTY = 3
SMART_PERCEPTION_RADIUS = 10

# --- 3. USTAWIENIA PREDATORA ---
PREDATOR_COUNT = 5
PREDATOR_RESPAWN = True
PREDATOR_VISION = 10
PREDATOR_BASE_STRENGTH = 5
PREDATOR_ALLY_BONUS = 2
PREDATOR_ALLY_RADIUS = 3
KILL_LICENSE_LEVEL = 2
KILL_COST_PELLETS = 1

# --- 4. USTAWIENIA UCZENIA (WSPÓLNE) ---
NUM_EPISODES = 2000
MAX_TURNS_PER_EPISODE = 1000
GAMMA = 0.99

# --- 5. USTAWIENIA MÓZGU AGENTA (DQN_AGENT) ---
AGENT_HIDDEN_LAYERS = [64, 32]
AGENT_LEARNING_RATE = 0.001
AGENT_MEMORY_SIZE = 50000
AGENT_BATCH_SIZE = 128
AGENT_EPS_START = 0.9
AGENT_EPS_END = 0.05
AGENT_EPS_DECAY = 30000

# --- 6. USTAWIENIA MÓZGU DRAPIEŻNIKA (DQN_PREDATOR) ---
PREDATOR_HIDDEN_LAYERS = [64, 32]
PREDATOR_LEARNING_RATE = 0.001
PREDATOR_MEMORY_SIZE = 50000
PREDATOR_BATCH_SIZE = 128
PREDATOR_EPS_START = 0.9
PREDATOR_EPS_END = 0.05
PREDATOR_EPS_DECAY = 20000

# --- 7. USTAWIENIA ZAPISU ---
MODEL_SAVE_DIR = "best_models_coevo_v36_strong_rewards" # <-- ZMIANA
LOG_FILE = f"log_wynikow_{MODEL_SAVE_DIR}.csv"

# --- 8. USTAWIENIA WIZUALIZACJI ---
CELL_SIZE = 14
WINDOW_WIDTH = GRID_WIDTH * CELL_SIZE
WINDOW_HEIGHT = GRID_HEIGHT * CELL_SIZE
FPS = 1000

# --- 9. KOLORY (RGB) ---
COLOR_BG = (20, 20, 20)
COLOR_FOOD = (0, 255, 0)
COLOR_AGENT = (0, 150, 255)
COLOR_PREDATOR = (255, 0, 0)
COLOR_GRID = (40, 40, 40)
COLOR_WALL = (100, 100, 100)

# --- 10. USTAWIENIA EARLY STOPPING ---
EARLY_STOPPING_ENABLED = True
EARLY_STOPPING_PATIENCE = 50      # Ile epizodów czekamy na poprawę rekordu
EARLY_STOPPING_WINDOW = 50        # Z ilu ostatnich epizodów liczymy średnią (wygładzanie wykresu)
EARLY_STOPPING_MIN_EPISODES = 100 # Minimalna liczba epizodów przed włączeniem sprawdzania