# config_dqn.py - TOTAL ECOSYSTEM EDITION

# --- 1. USTAWIENIA ŚWIATA ---
GRID_WIDTH = 40
GRID_HEIGHT = 40
NUM_FOOD = 60
NUM_WALLS = 40
NUM_MUD = 50

# --- 2. USTAWIENIA AGENTA (Biology) ---
START_ENERGY = 100
MAX_AGE = 400
REPRODUCTION_THRESHOLD = 600
REPRODUCTION_COST = 300
MAX_POPULATION = 60

EAT_GAIN = 100
MAX_ENERGY_GAIN_PER_FOOD = 10

# Koszty akcji
MOVE_COST = 1
MUD_MOVE_COST = 3
IDLE_COST = 2
DASH_COST = 5
CAMO_COST = 2
WALL_HIT_PENALTY = 5

SMART_PERCEPTION_RADIUS = 10

# --- 3. USTAWIENIA PREDATORA (Biology Update) ---
PREDATOR_START_ENERGY = 150    # Startowa energia
PREDATOR_MAX_AGE = 800         # Żyją dłużej niż agenci
PREDATOR_REPRODUCTION_THRESHOLD = 500 # Muszą zjeść kilku agentów, by się rozmnożyć
PREDATOR_REPRODUCTION_COST = 250
PREDATOR_MAX_POPULATION = 15   # Limit, żeby nie zjedli całej mapy w sekundę
PREDATOR_EAT_GAIN = 200        # Energia za zjedzenie agenta

PREDATOR_COUNT_START = 4       # Populacja startowa
PREDATOR_RESPAWN = True        # Czy ratować gatunek przed wyginięciem (jeśli < 2 sztuki)

PREDATOR_VISION = 10
PREDATOR_BASE_STRENGTH = 5
SNIFF_COST = 3

# Mechanika Feromonów
SCENT_DECAY = 0.90
SCENT_ADDED = 1.0

# Mechanika Zabijania
KILL_LICENSE_LEVEL = 5
KILL_COST_PELLETS = 1

# --- 4. USTAWIENIA UCZENIA ---
NUM_EPISODES = 5000
MAX_TURNS_PER_EPISODE = 2000   # Dłuższe epizody
GAMMA = 0.99

# --- 5. SIEĆ AGENTA ---
AGENT_INPUT_SIZE = 22
AGENT_OUTPUT_SIZE = 7
AGENT_HIDDEN_LAYERS = [128, 64]

AGENT_LEARNING_RATE = 0.001
AGENT_MEMORY_SIZE = 50000
AGENT_BATCH_SIZE = 128
AGENT_EPS_START = 1.0
AGENT_EPS_END = 0.05
AGENT_EPS_DECAY = 10000

# --- 6. SIEĆ DRAPIEŻNIKA ---
PREDATOR_INPUT_SIZE = 14
PREDATOR_OUTPUT_SIZE = 7
PREDATOR_HIDDEN_LAYERS = [128, 64]

PREDATOR_LEARNING_RATE = 0.001
PREDATOR_MEMORY_SIZE = 50000
PREDATOR_BATCH_SIZE = 128
PREDATOR_EPS_START = 1.0
PREDATOR_EPS_END = 0.05
PREDATOR_EPS_DECAY = 10000

# --- 7. ZAPIS I EARLY STOPPING ---
MODEL_SAVE_DIR = "models_ecosystem_v1"
LOG_FILE = f"log_wynikow_{MODEL_SAVE_DIR}.csv"

EARLY_STOPPING_ENABLED = True
EARLY_STOPPING_PATIENCE = 100
EARLY_STOPPING_WINDOW = 50
EARLY_STOPPING_MIN_EPISODES = 100

# --- 8. WIZUALIZACJA ---
CELL_SIZE = 14
WINDOW_WIDTH = GRID_WIDTH * CELL_SIZE
WINDOW_HEIGHT = GRID_HEIGHT * CELL_SIZE
FPS = 1000

# --- 9. KOLORY ---
COLOR_BG = (20, 20, 20)
COLOR_FOOD = (0, 255, 0)
COLOR_AGENT = (0, 150, 255)
COLOR_AGENT_CAMO = (80, 80, 80)
COLOR_PREDATOR = (255, 0, 0)
COLOR_PREDATOR_CAMO = (100, 0, 0) # Ciemniejszy czerwony gdy węszą
COLOR_GRID = (40, 40, 40)
COLOR_WALL = (100, 100, 100)
COLOR_MUD = (101, 67, 33)